# This runs `cargo clippy` on everything.

name: Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~/.cargo
          target
        key: clippy
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Clippy
      run: cargo clippy --all-features
