# This clippys, docs, tests, builds.

name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~/.cargo
          target
        key: linux
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Clippy
      run: cargo clippy --all-features
    - name: Doc
      run: RUSTFLAGS='-D warnings' cargo doc --workspace --no-deps --all-features
    - name: Test
      run: cargo test --all-features
    - name: Build
      run: cargo build --all-features
